# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_opp', '0006_auto_20170802_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='entity_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checkout_id',
            field=models.CharField(default='', editable=False, max_length=48, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='correlation_id',
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='result_description',
            field=models.CharField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
    ]
